name: Build mcMMO

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Step 1: Clone the repo and prep for build
      - name: Clone mcMMO repository
        run: git clone https://github.com/mcMMO-Dev/mcMMO.git

      # Step 2: Set up the Java environment required for building
      # mcMMO requires Java 17
      # but we will use 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Cache Maven packages to speed up future builds
          cache: 'maven'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: |
          cd mcMMO
          mvn -B package --file pom.xml

      # Step 4: Create the GitHub Release and upload the artifact
      # This uses the popular `softprops/action-gh-release` action
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # The tag name for the release. Uses the run number to ensure uniqueness.
          tag_name: mcMMO-build-${{ github.run_number }}

          name: mcMMO Build ${{ github.run_number }}

          # A description for the release body.
          body: |
            This is an automated build of mcMMO.
            Triggered by commit: ${{ github.sha }}
          
          # Specifies the files to upload as release assets.
          files: mcMMO/target/mcMMO.jar
